FLASK_PORT = 80
DEBUG_STATUS = True

# CNN
CNN_N_FILTERS = 64
CNN_KERNEL_SIZE = (3,3)
CNN_POOL_SIZE = (2,2)
CNN_CONV_ACTIVATION_FUNCTION = 'relu'
CNN_OUTPUT_ACTIVATION_FUNCTION = 'sigmoid'
CNN_DENSE_NODE_COUNT = 64
CNN_OUTPUT_DENSE_NODE_COUNT = 1
CNN_LOSS_FUNCTION = 'binary_crossentropy'
CNN_OPTIMIZER = 'adam'
CNN_METRICS = ['accuracy']
CNN_MATCH_SIZE = 32
CNN_EPOCHS = 3
CNN_VALIDATION_SPLIT = 0.1